import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
   return (
      <div>
         <Head>
            <title>Kanban Task Management</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/assets/favicon-32x32.png" />
         </Head>

         <div className=" flex h-screen bg-lightGrey ">
            <div className="m-auto text-center">
               <p className="px-10 font-semibold text-mediumGrey">This board is empty. Create a new column to get started.</p>
               <button className="rounded-full bg-purple py-2 px-3 mt-2 text-white text-xs">+Add New Colum</button>
            </div>
         </div>
      </div>
   )
}

export default Home
